service: curd-auth

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    MONGO_URI: ${env:MONGO_URI}

    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRE: ${env:JWT_EXPIRE}
    COINBASE_CLIENT_ID: ${env:COINBASE_CLIENT_ID}
    COINBASE_CLIENT_SECRET: ${env:COINBASE_CLIENT_SECRET}
    COINBASE_REDIRECT_URI: ${env:COINBASE_REDIRECT_URI}

    ENCRYPTION_KEY: ${env:ENCRYPTION_KEY}

    AUTH_REDIRECT_URI: ${env:AUTH_REDIRECT_URI}




functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'